### ISSUE TITLE
please tag release 0.07 in git

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-Text-sprintfn#1]
It seems you forgot to tag release 0.07 now in CPAN - or perhaps just forgot to push the tag - i.e. do "git push --tags".

**Comment by jonassmedegaard** [comment]
Please tag release 0.08 too.

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

Done, thanks!
